# Setup
title:        Hui Li
tagline:      PRCI Lab, Jiangnan University.
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Hui Li
  url:        https://hli1221.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
theme: jekyll-theme-minimal